districts_mock = [
    {
        "id": "demo-1",
        "district_name": "Metro-Rural Periphery (Featured Demo Case)",
        "type": "Mixed",
        "population": 1200000,
        "bpl_ratio": 65.0,
        "vulnerable_household_ratio": 50.0,
        "hospital_demand_index": 60.0,
        "current_lpg_stock": 40.0,
        "expected_refill_demand": 75.0,
        "road_access_score": 85.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 75.0,
        "diversion_risk_score": 60.0,
        "urban_induction_shift_percent": 45.0,
        "rural_lpg_dependency_percent": 95.0,
        "recent_supply_drop_percent": 15.0,
        "last_mile_feasibility_score": 90.0,
        "narrative": "Featured case: Urban users shifting to induction, but high rural dependency and high urban leakage. Needs subsidy targeting.",
        "expected_band": "High Priority",
        "expected_recommendation": "Shift subsidy priority"
    },
    {
        "id": "rural-1",
        "district_name": "Rural Sector Alpha (High Priority)",
        "type": "Rural",
        "population": 150000,
        "bpl_ratio": 85.0,
        "vulnerable_household_ratio": 75.0,
        "hospital_demand_index": 80.0,
        "current_lpg_stock": 10.0,
        "expected_refill_demand": 95.0,
        "road_access_score": 70.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 10.0,
        "diversion_risk_score": 15.0,
        "urban_induction_shift_percent": 5.0,
        "rural_lpg_dependency_percent": 98.0,
        "recent_supply_drop_percent": 40.0,
        "last_mile_feasibility_score": 65.0,
        "narrative": "A deeply vulnerable rural district with extremely low LPG stock.",
        "expected_band": "Critical Priority",
        "expected_recommendation": "Increase LPG allocation urgently"
    },
    {
        "id": "urban-1",
        "district_name": "Tech City Central (Urban Moderate)",
        "type": "Urban",
        "population": 2000000,
        "bpl_ratio": 15.0,
        "vulnerable_household_ratio": 10.0,
        "hospital_demand_index": 45.0,
        "current_lpg_stock": 80.0,
        "expected_refill_demand": 40.0,
        "road_access_score": 95.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 40.0,
        "diversion_risk_score": 30.0,
        "urban_induction_shift_percent": 60.0,
        "rural_lpg_dependency_percent": 5.0,
        "recent_supply_drop_percent": 5.0,
        "last_mile_feasibility_score": 95.0,
        "narrative": "Affluent urban area rapidly shifting to induction. Low priority overall.",
        "expected_band": "Moderate Monitoring",
        "expected_recommendation": "Maintain allocation"
    },
    {
        "id": "fraud-1",
        "district_name": "Border Trade Zone (Fraud Risk Flagged)",
        "type": "Urban/Commercial",
        "population": 500000,
        "bpl_ratio": 40.0,
        "vulnerable_household_ratio": 30.0,
        "hospital_demand_index": 50.0,
        "current_lpg_stock": 60.0,
        "expected_refill_demand": 80.0,
        "road_access_score": 90.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 95.0,
        "diversion_risk_score": 90.0,
        "urban_induction_shift_percent": 20.0,
        "rural_lpg_dependency_percent": 40.0,
        "recent_supply_drop_percent": 35.0,
        "last_mile_feasibility_score": 85.0,
        "narrative": "High risk of commercial diversion. Subsidy leakage is extreme.",
        "expected_band": "High Priority",
        "expected_recommendation": "Flag for fraud / misuse review"
    },
    {
        "id": "hard-1",
        "district_name": "Mountain Valley (High Need / Low Feasibility)",
        "type": "Rural/Remote",
        "population": 80000,
        "bpl_ratio": 80.0,
        "vulnerable_household_ratio": 70.0,
        "hospital_demand_index": 70.0,
        "current_lpg_stock": 15.0,
        "expected_refill_demand": 85.0,
        "road_access_score": 20.0,
        "flood_or_disruption_flag": True,
        "black_market_risk_score": 5.0,
        "diversion_risk_score": 5.0,
        "urban_induction_shift_percent": 0.0,
        "rural_lpg_dependency_percent": 100.0,
        "recent_supply_drop_percent": 50.0,
        "last_mile_feasibility_score": 10.0,
        "narrative": "Landslide has blocked access. Need is extreme but delivery is impossible normally.",
        "expected_band": "High Priority",
        "expected_recommendation": "Route priority delivery support"
    },
    {
        "id": "dist-6",
        "district_name": "Delta Flats (Flood Crisis)",
        "type": "Rural",
        "population": 300000,
        "bpl_ratio": 65.0,
        "vulnerable_household_ratio": 60.0,
        "hospital_demand_index": 90.0,
        "current_lpg_stock": 25.0,
        "expected_refill_demand": 95.0,
        "road_access_score": 40.0,
        "flood_or_disruption_flag": True,
        "black_market_risk_score": 15.0,
        "diversion_risk_score": 20.0,
        "urban_induction_shift_percent": 10.0,
        "rural_lpg_dependency_percent": 85.0,
        "recent_supply_drop_percent": 30.0,
        "last_mile_feasibility_score": 30.0,
        "narrative": "Severe flooding causing sudden hospital and shelter demand.",
        "expected_band": "Critical Priority",
        "expected_recommendation": "Route priority delivery support"
    },
    {
        "id": "dist-7",
        "district_name": "Northern Suburbs (Low Need)",
        "type": "Sub-Urban",
        "population": 600000,
        "bpl_ratio": 20.0,
        "vulnerable_household_ratio": 15.0,
        "hospital_demand_index": 40.0,
        "current_lpg_stock": 70.0,
        "expected_refill_demand": 45.0,
        "road_access_score": 90.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 10.0,
        "diversion_risk_score": 15.0,
        "urban_induction_shift_percent": 40.0,
        "rural_lpg_dependency_percent": 20.0,
        "recent_supply_drop_percent": 5.0,
        "last_mile_feasibility_score": 90.0,
        "narrative": "Stable suburban area with high pipeline/induction usage.",
        "expected_band": "Low Priority / Manual Review",
        "expected_recommendation": "Manual policy review required"
    },
    {
        "id": "dist-8",
        "district_name": "Industrial Port (Supply Shock)",
        "type": "Urban",
        "population": 900000,
        "bpl_ratio": 35.0,
        "vulnerable_household_ratio": 30.0,
        "hospital_demand_index": 60.0,
        "current_lpg_stock": 30.0,
        "expected_refill_demand": 85.0,
        "road_access_score": 85.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 50.0,
        "diversion_risk_score": 60.0,
        "urban_induction_shift_percent": 20.0,
        "rural_lpg_dependency_percent": 15.0,
        "recent_supply_drop_percent": 40.0,
        "last_mile_feasibility_score": 85.0,
        "narrative": "Strike causing local supply drop, rising panic demand.",
        "expected_band": "High Priority",
        "expected_recommendation": "Increase LPG allocation urgently"
    },
    {
        "id": "dist-9",
        "district_name": "Agri-Belt West (Stable Rural)",
        "type": "Rural",
        "population": 400000,
        "bpl_ratio": 50.0,
        "vulnerable_household_ratio": 40.0,
        "hospital_demand_index": 40.0,
        "current_lpg_stock": 65.0,
        "expected_refill_demand": 60.0,
        "road_access_score": 75.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 10.0,
        "diversion_risk_score": 10.0,
        "urban_induction_shift_percent": 5.0,
        "rural_lpg_dependency_percent": 80.0,
        "recent_supply_drop_percent": 10.0,
        "last_mile_feasibility_score": 75.0,
        "narrative": "Typical rural setting with balanced supply and demand.",
        "expected_band": "Moderate Monitoring",
        "expected_recommendation": "Maintain allocation"
    },
    {
        "id": "dist-10",
        "district_name": "Urban Slum Cluster (Critical Density)",
        "type": "Urban",
        "population": 1500000,
        "bpl_ratio": 75.0,
        "vulnerable_household_ratio": 65.0,
        "hospital_demand_index": 85.0,
        "current_lpg_stock": 25.0,
        "expected_refill_demand": 95.0,
        "road_access_score": 60.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 40.0,
        "diversion_risk_score": 30.0,
        "urban_induction_shift_percent": 10.0,
        "rural_lpg_dependency_percent": 0.0,
        "recent_supply_drop_percent": 30.0,
        "last_mile_feasibility_score": 50.0,
        "narrative": "Very dense vulnerability. High risk of supply-run panic.",
        "expected_band": "Critical Priority",
        "expected_recommendation": "Increase LPG allocation urgently"
    },
    {
        "id": "dist-11",
        "district_name": "Heritage Tourism Zone (Demand Spike)",
        "type": "Urban/Mixed",
        "population": 250000,
        "bpl_ratio": 30.0,
        "vulnerable_household_ratio": 25.0,
        "hospital_demand_index": 60.0,
        "current_lpg_stock": 40.0,
        "expected_refill_demand": 90.0,
        "road_access_score": 80.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 55.0,
        "diversion_risk_score": 45.0,
        "urban_induction_shift_percent": 25.0,
        "rural_lpg_dependency_percent": 30.0,
        "recent_supply_drop_percent": 15.0,
        "last_mile_feasibility_score": 85.0,
        "narrative": "Tourist influx draining residential stock.",
        "expected_band": "Moderate Monitoring",
        "expected_recommendation": "Maintain allocation"
    },
    {
        "id": "dist-12",
        "district_name": "Eastern Mining District (Logistics Snag)",
        "type": "Mixed",
        "population": 350000,
        "bpl_ratio": 55.0,
        "vulnerable_household_ratio": 50.0,
        "hospital_demand_index": 55.0,
        "current_lpg_stock": 50.0,
        "expected_refill_demand": 65.0,
        "road_access_score": 45.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 25.0,
        "diversion_risk_score": 30.0,
        "urban_induction_shift_percent": 10.0,
        "rural_lpg_dependency_percent": 60.0,
        "recent_supply_drop_percent": 20.0,
        "last_mile_feasibility_score": 40.0,
        "narrative": "Rough roads making standard delivery trucks fail constantly.",
        "expected_band": "High Priority",
        "expected_recommendation": "Increase LPG allocation urgently"
    },
    {
        "id": "dist-13",
        "district_name": "Capital City (Pipeline Area)",
        "type": "Urban",
        "population": 3000000,
        "bpl_ratio": 10.0,
        "vulnerable_household_ratio": 5.0,
        "hospital_demand_index": 30.0,
        "current_lpg_stock": 90.0,
        "expected_refill_demand": 20.0,
        "road_access_score": 100.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 20.0,
        "diversion_risk_score": 10.0,
        "urban_induction_shift_percent": 70.0,
        "rural_lpg_dependency_percent": 0.0,
        "recent_supply_drop_percent": 0.0,
        "last_mile_feasibility_score": 100.0,
        "narrative": "Has piped gas and induction. Barely needs cylinder LPG.",
        "expected_band": "Low Priority / Manual Review",
        "expected_recommendation": "Manual policy review required"
    },
    {
        "id": "dist-14",
        "district_name": "Coastal Village Array (Storm Alert)",
        "type": "Rural",
        "population": 120000,
        "bpl_ratio": 70.0,
        "vulnerable_household_ratio": 65.0,
        "hospital_demand_index": 75.0,
        "current_lpg_stock": 35.0,
        "expected_refill_demand": 85.0,
        "road_access_score": 50.0,
        "flood_or_disruption_flag": True,
        "black_market_risk_score": 5.0,
        "diversion_risk_score": 5.0,
        "urban_induction_shift_percent": 2.0,
        "rural_lpg_dependency_percent": 95.0,
        "recent_supply_drop_percent": 25.0,
        "last_mile_feasibility_score": 35.0,
        "narrative": "Cyclone warning. Needs preventive stocking.",
        "expected_band": "High Priority",
        "expected_recommendation": "Route priority delivery support"
    },
    {
        "id": "dist-15",
        "district_name": "Refugee Settlement (Extreme Need)",
        "type": "Rural",
        "population": 90000,
        "bpl_ratio": 95.0,
        "vulnerable_household_ratio": 90.0,
        "hospital_demand_index": 95.0,
        "current_lpg_stock": 5.0,
        "expected_refill_demand": 100.0,
        "road_access_score": 60.0,
        "flood_or_disruption_flag": False,
        "black_market_risk_score": 15.0,
        "diversion_risk_score": 10.0,
        "urban_induction_shift_percent": 0.0,
        "rural_lpg_dependency_percent": 100.0,
        "recent_supply_drop_percent": 60.0,
        "last_mile_feasibility_score": 55.0,
        "narrative": "Complete supply collapse. Immediate survival risk.",
        "expected_band": "Critical Priority",
        "expected_recommendation": "Increase LPG allocation urgently"
    }
]
